# Generated by Django 3.0.4 on 2020-03-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('weight', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('weight_kcal', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('volume', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('volume_kcal', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
