# Generated by Django 3.0.4 on 2020-03-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodProducts',
            new_name='FoodProduct',
        ),
    ]
