# Generated by Django 3.0.4 on 2020-03-11 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0002_auto_20200311_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='volume',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='volume_kcal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='weight_kcal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
