# Generated by Django 3.0.4 on 2020-03-11 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0005_auto_20200311_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='fat_per_100ml',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
