# Generated by Django 3.0.4 on 2020-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0010_auto_20200312_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='food_products',
            field=models.ManyToManyField(to='diet_diary.FoodProduct'),
        ),
    ]
