# Generated by Django 3.0.4 on 2020-03-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0011_dish_food_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='food_products',
        ),
    ]
