# Generated by Django 3.0.4 on 2020-03-16 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0012_remove_dish_food_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_product_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.Dish')),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.FoodProduct')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='food_products',
            field=models.ManyToManyField(through='diet_diary.DishDetails', to='diet_diary.FoodProduct'),
        ),
    ]
