# Generated by Django 3.0.4 on 2020-03-21 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0013_auto_20200316_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='carbs_per_100g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat_per_100g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein_per_100g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
