# Generated by Django 3.0.4 on 2020-03-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0014_auto_20200321_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='carbs_per_100g',
            new_name='dish_carbs',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='fat_per_100g',
            new_name='dish_fat',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='protein_per_100g',
            new_name='dish_protein',
        ),
    ]
