# Generated by Django 3.0.4 on 2020-03-21 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0015_auto_20200321_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(max_length=512)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.TrainingTypes')),
            ],
        ),
    ]
