# Generated by Django 3.0.4 on 2020-03-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0016_training_trainingtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.CharField(max_length=512)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.Training')),
            ],
        ),
        migrations.CreateModel(
            name='DishPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.CharField(max_length=512)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.DishDetails')),
            ],
        ),
    ]
