# Generated by Django 3.0.4 on 2020-03-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0017_dishplan_trainingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishplan',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_diary.Dish'),
        ),
    ]
