# Generated by Django 3.0.4 on 2020-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0018_auto_20200321_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishplan',
            name='notes',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
