# Generated by Django 3.0.4 on 2020-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0019_auto_20200321_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='notes',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='notes',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
